using System.Net;
using System.Text;

namespace PCGuardian;

internal static class ReportGenerator
{
    public static string ToHtml(Report report)
    {
        var sb = new StringBuilder();
        var host = Environment.MachineName;
        var date = report.Timestamp.ToString("MMMM d, yyyy \u2014 h:mm tt");
        var overall = report.Overall;
        var statusColor = overall switch { Status.Safe => "#10b981", Status.Warning => "#f59e0b", _ => "#ef4444" };
        var statusBg = overall switch { Status.Safe => "#ecfdf5", Status.Warning => "#fffbeb", _ => "#fef2f2" };
        var statusText = overall switch
        {
            Status.Safe => "Your PC looks secure",
            Status.Warning => "A few things to review",
            _ => "Some things need your attention",
        };

        sb.AppendLine("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">");
        sb.AppendLine($"<title>PC Guardian Report \u2014 {WebUtility.HtmlEncode(host)}</title>");
        sb.AppendLine("<style>");
        sb.AppendLine(CSS);
        sb.AppendLine("</style></head><body>");

        // Header
        sb.AppendLine("<div class=\"header\">");
        sb.AppendLine("<div class=\"logo\">\uD83D\uDEE1\uFE0F PC Guardian</div>");
        var adminTag = AdminHelper.IsAdmin() ? "Full access" : "Limited mode (not running as admin)";
        sb.AppendLine($"<div class=\"meta\">{WebUtility.HtmlEncode(host)} &middot; {WebUtility.HtmlEncode(date)} &middot; {adminTag}</div>");
        sb.AppendLine("</div>");

        // Overall status
        sb.AppendLine($"<div class=\"status-banner\" style=\"background:{statusBg};border-left:4px solid {statusColor}\">");
        sb.AppendLine($"<div class=\"status-title\" style=\"color:{statusColor}\">{WebUtility.HtmlEncode(statusText)}</div>");
        sb.AppendLine($"<div class=\"status-stats\">{report.SafeCount} of {report.Categories.Count} checks passed");
        if (report.WarningCount > 0) sb.Append($" &middot; {report.WarningCount} to review");
        if (report.DangerCount > 0) sb.Append($" &middot; {report.DangerCount} need attention");
        sb.AppendLine("</div></div>");

        // Categories
        foreach (var cat in report.Categories)
        {
            var catColor = cat.Status switch { Status.Safe => "#10b981", Status.Warning => "#f59e0b", _ => "#ef4444" };
            var catBg = cat.Status switch { Status.Safe => "#f0fdf4", Status.Warning => "#fffbeb", _ => "#fef2f2" };
            var badge = cat.Status switch { Status.Safe => "All Good", Status.Warning => "Worth Checking", _ => "Needs Attention" };

            sb.AppendLine("<div class=\"card\">");
            sb.AppendLine($"<div class=\"card-bar\" style=\"background:{catColor}\"></div>");
            sb.AppendLine("<div class=\"card-body\">");

            // Header row
            sb.AppendLine("<div class=\"card-header\">");
            sb.AppendLine($"<span class=\"card-icon\">{cat.Icon}</span>");
            sb.AppendLine($"<span class=\"card-title\">{WebUtility.HtmlEncode(cat.Title)}</span>");
            sb.AppendLine($"<span class=\"badge\" style=\"background:{catBg};color:{catColor}\">{badge}</span>");
            sb.AppendLine("</div>");

            sb.AppendLine($"<div class=\"card-summary\">{WebUtility.HtmlEncode(cat.Summary)}</div>");

            // Findings
            sb.AppendLine("<div class=\"findings\">");
            foreach (var f in cat.Findings)
            {
                var dotColor = f.Status switch { Status.Safe => "#10b981", Status.Warning => "#f59e0b", _ => "#ef4444" };
                sb.AppendLine("<div class=\"finding\">");
                sb.AppendLine($"<span class=\"dot\" style=\"color:{dotColor}\">\u25CF</span>");
                sb.AppendLine("<div>");
                sb.AppendLine($"<div class=\"finding-label\">{WebUtility.HtmlEncode(f.Label)}</div>");
                sb.AppendLine($"<div class=\"finding-detail\">{WebUtility.HtmlEncode(f.Detail)}</div>");
                sb.AppendLine("</div></div>");
            }
            sb.AppendLine("</div>");

            // Tip
            sb.AppendLine($"<div class=\"tip\"><strong>What to do:</strong> {WebUtility.HtmlEncode(cat.Tip)}</div>");

            sb.AppendLine("</div></div>"); // card-body, card
        }

        // Footer
        sb.AppendLine("<div class=\"footer\">");
        sb.AppendLine($"Generated by PC Guardian on {WebUtility.HtmlEncode(date)}");
        sb.AppendLine("<br>This report is a snapshot \u2014 run a new scan for the latest results.");
        sb.AppendLine("</div>");

        sb.AppendLine("</body></html>");
        return sb.ToString();
    }

    public static void SaveToFile(Report report, string path)
    {
        File.WriteAllText(path, ToHtml(report), Encoding.UTF8);
    }

    const string CSS = """
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
            background: #fafafa; color: #1a1a1a; padding: 32px;
            max-width: 800px; margin: 0 auto; line-height: 1.5;
        }
        .header { margin-bottom: 24px; }
        .logo { font-size: 24px; font-weight: 700; }
        .meta { font-size: 13px; color: #666; margin-top: 4px; }
        .status-banner {
            padding: 16px 20px; border-radius: 10px; margin-bottom: 24px;
        }
        .status-title { font-size: 18px; font-weight: 600; }
        .status-stats { font-size: 13px; color: #555; margin-top: 4px; }
        .card {
            display: flex; border: 1px solid #e5e5e5; border-radius: 10px;
            overflow: hidden; margin-bottom: 12px; background: #fff;
        }
        .card-bar { width: 4px; flex-shrink: 0; }
        .card-body { padding: 16px 20px; flex: 1; }
        .card-header { display: flex; align-items: center; gap: 8px; margin-bottom: 4px; }
        .card-icon { font-size: 20px; }
        .card-title { font-size: 15px; font-weight: 600; }
        .badge {
            font-size: 11px; font-weight: 600; padding: 2px 10px;
            border-radius: 99px; margin-left: auto;
        }
        .card-summary { font-size: 13px; color: #555; margin-bottom: 12px; }
        .findings { margin-bottom: 12px; }
        .finding {
            display: flex; align-items: flex-start; gap: 8px;
            padding: 4px 0; font-size: 13px;
        }
        .dot { font-size: 8px; margin-top: 5px; flex-shrink: 0; }
        .finding-label { font-weight: 600; }
        .finding-detail { color: #666; font-size: 12px; }
        .tip {
            font-size: 12px; color: #555; padding-top: 10px;
            border-top: 1px solid #eee;
        }
        .footer {
            text-align: center; font-size: 12px; color: #999;
            margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee;
        }
        @media print {
            body { padding: 16px; }
            .card { break-inside: avoid; }
        }
    """;
}
